-- AUTO-GENERATED by matugen — do not edit directly
-- Edit ~/dotfiles/theme/matugen/templates/colors.lua to change structure

return {
  bg                   = "{{colors.surface.default.hex}}",
  surface_low          = "{{colors.surface_container_low.default.hex}}",
  surface              = "{{colors.surface_container.default.hex}}",
  surface_high         = "{{colors.surface_container_high.default.hex}}",
  overlay              = "{{colors.surface_container_highest.default.hex}}",
  fg                   = "{{colors.on_surface.default.hex}}",
  fg_dim               = "{{colors.on_surface_variant.default.hex}}",
  fg_muted             = "{{colors.outline.default.hex}}",
  border               = "{{colors.outline_variant.default.hex}}",
  accent               = "{{colors.primary.default.hex}}",
  accent_alt           = "{{colors.tertiary.default.hex}}",
  accent_muted         = "{{colors.secondary.default.hex}}",
  on_accent            = "{{colors.on_primary.default.hex}}",
  accent_container     = "{{colors.primary_container.default.hex}}",
  on_accent_container  = "{{colors.on_primary_container.default.hex}}",
  danger               = "{{colors.error.default.hex}}",
  warning              = "{{colors.tertiary_container.default.hex}}",
  success              = "{{colors.secondary_container.default.hex}}",
}
