-- AUTO-GENERATED by matugen — do not edit directly
-- Edit ~/dotfiles/theme/matugen/templates/colors.lua to change structure

return {
  bg                   = "#fef9eb",
  surface_low          = "#f8f3e6",
  surface              = "#f2eee0",
  surface_high         = "#ece8db",
  overlay              = "#e7e2d5",
  fg                   = "#1d1c14",
  fg_dim               = "#49473a",
  fg_muted             = "#7a7768",
  border               = "#cac7b5",
  accent               = "#656015",
  accent_alt           = "#3f6654",
  accent_muted         = "#625f42",
  on_accent            = "#ffffff",
  accent_container     = "#ece68d",
  on_accent_container  = "#1e1c00",
  danger               = "#ba1a1a",
  warning              = "#c1ecd6",
  success              = "#e8e4be",
}
